### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by pamymaf** [andersfylling/jailbot#2]
Suggestion/Request - 

Allow us to set a mod channel in the config and have the bot alert us when a user in the database enters the server.

**Comment by andersfylling** [comment]
Bot will prioritize any channel named `jailbot-alerts` to post updates/warnings, and I will add in the options for moderators to set a custom channel as well.

**Comment by andersfylling** [comment]
This task will target two goals:
 - command to get member records (ban, kicks, etc)
 - notify the server when a new member with a "criminal" record joins
